# Site settings
title: El Placer de Comer
description: Promovemos un estilo de vida más saludable a través de la educación alimentaria. ¡Cuidamos tu bienestar, porque comer bien, tambien es un placer!
url: 'http://elplacerdecomer.com.py'
baseurl: ''
keywords: salut, alimentacion, daisy ferreira, comer, saludable, nutricionista en paraguay, estilo de vida, educacion alimentaria, dietas, comida sana, adulto mayor

sass:
  style: compressed

# User settings
site_title: El Placer de Comer
site_description: Promovemos un estilo de vida mas saludable a través de la educacion alimentaria. Capacitaciones individuales o grupales, en consultorio o en el lugar que prefieras. ¡Cuidamos tu bienestar, porque comer bien, tambien es un placer!
professional_title: Msc Salud Pública - Nutricionista
professional_name: Daisy Ferreira
email: daisyferreira.g@gmail.com
#twitter_id: lorem_ipsum
#github_id:  lorem_ipsum
facebook_id: dfnutricionysalud
instagram_id: dfelplacerdecomer

exclude: ['package.json', 'src' , 'node_modules', 'gulpfile.js', 'README.md', 'LICENSE.txt', 'package-lock.json']
