# Site settings
title: El Placer de Comer
description: Promoviendo un estilo de vida saludable
#url: '/'
baseurl: 'https://daisyferreirag.github.io/salud_alimentacion' #change it according to your repository name

# User settings
site_title: El Placer de Comer
site_description: Promovemos un estilo de vida mas saludable a través de la educacion alimentaria. Capacitaciones individuales o grupales, en consultorio o en el lugar que prefiera. ¡Cuidamos tu bienestar, porque comer, tambien es un placer!
professional_title: Msc Salud Pública - Nutricionista
professional_name: Daisy Ferreira
email: daisyferreira.g@gmail.com
#twitter_id: lorem_ipsum
#github_id:  lorem_ipsum
facebook_id: dfnutricionysalud
instagram_id: daisyferreirasalud

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules', 'gulpfile.js', 'README.md', 'LICENSE.txt', 'package-lock.json']
