- name: Consultorio de Nutrición
  description: Mediante la consulta nutricional, se determina el estado nutricional del paciente. Según los resultados, se realiza una planificación de la alimentación para mantener o mejorar el estado de salud y el bienestar.
  image: balanza

- name: Controles de Consulta
  description: En los controles, se evalua la continuidad del plan alimentario, se visualizan los resultados y se agregan las modificaciones pertinentes a un nuevo plan alimentario.
  image: fruta

- name: Educación Alimentaria
  description: A través de estrategias educativas te brindamos las nociones básicas para que adoptes de manera voluntaria conductas alimentarias saludables propicias para tu salud y tu bienestar.
  image: brocoli

- name: Taller de Alimentación 
  description: A través de este taller de 10hs, te brindamos conocimientos sobre los grupos alimentarios, sus cualidades nutricionales, el efecto en la salud de su transformación alimentaria y cómo elaborar la distribución de las comidas de manera diaria y semanal.
  image: tenedor
